services:
  - type: web
    name: meubly-back
    env: node
    buildCommand: cd meubly-back && npm install
    startCommand: cd meubly-back && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: "https://rlxyptqvtpdhrdpdoiwy.supabase.co"
      - key: SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseHlwdHF2dHBkaHJkcGRvaXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzY2NDcsImV4cCI6MjA1NzM1MjY0N30.QXV4iki_U8Q9d1G_RspNxFqcd2plLbYod8lEA6pLxHY"
    rootDir: .